Added support for webhook parsing
apeinot/DD2480_lab2_group18 pull request #14
Opened 2019-02-03 15:36 UTC by Samuelhertzberg

Added a file and class "RequestParser.java"

The class contains the method 'parse' which is passed a HttpServletRequest which is parsed to a JSONObject. Then the appropriate fields are extracted.

This should resolve issue #8

2019-02-03 16:08 UTC, apeinot requested changes
Your function and test looks good. They resolve #8 
Can you also parse the following fields that will be usefull for commands:
- repository/clone_url
- repository/name

Add `package CIserver;` at the beginning of your main class file

2019-02-03 16:13 UTC, francislaus approved these changes

2019-02-03 16:15 UTC, francislaus commented
Apart from what @apeinot requested, I think that the implementation and documentation of both the function itself and the test cases looks good.

2019-02-03 16:18 UTC, Jonagoo requested changes
Which method is supposed to be called from the main method? I assume it is parse, in which case I think a few more fields from the json is needed as getters, the ssh-url in particular for cloning as well as the name of the repository for more convenient running of tests.

Aside from this everything looks good.

2019-02-03 16:21 UTC, apeinot commented
> Which method is supposed to be called from the main method? I assume it is parse, in which case I think a few more fields from the json is needed as getters, the ssh-url in particular for cloning as well as the name of the repository for more convenient running of tests.

I think the clone_url that I asked for is enough (we don't need the ssh_url to clone)

2019-02-03 16:25 UTC, Jonagoo commented
> > Which method is supposed to be called from the main method? I assume it is parse, in which case I think a few more fields from the json is needed as getters, the ssh-url in particular for cloning as well as the name of the repository for more convenient running of tests.
> 
> I think the clone_url that I asked for is enough (we don't need the ssh_url to clone)

You're probably correct, I've just always went with ssh when cloning so that was the one I recognised.

2019-02-04 12:53 UTC, Samuelhertzberg commented
Will fix asap

2019-02-05 12:38 UTC, Jonagoo commented
Another good thing would be to give some sort of return code to see if parse() executed successfully. Just returning a 0 if it's successful and 1 otherwise or something similar would help prevent exceptions later in the code.

2019-02-05 19:15 UTC, Samuelhertzberg commented
Changed committed and pushed. Error codes specified in parse() doc-comments.

2019-02-06 08:18 UTC, Jonagoo approved these changes

2019-02-06 08:52 UTC, emilelmarsson commented on src/main/java/RequestParser.java
> +    @return The status code. 1 for success, 0 for connection/response issues and -1 for parsing issues.
The parse() function doesn't seem to return -1 when there are parsing issues like specified in the documentation.

2019-02-06 09:37 UTC, emilelm96 approved these changes

2019-02-06 09:40 UTC, apeinot approved these changes

2019-02-06 09:41 UTC, merged